Homework 4
infinum-academy/js-react-academy-2024-dadadavorin pull request #4
Opened 2024-07-14 16:37 UTC by dadadavorin

This will enhance the app with following functionalities:

- Register and Login via the API
- Improve on forms by using React Form Hook, adding validation and error messages
- Migrate data fetching from the real API
- Update StarInputRating component to use react form hook and connect it with the review form component

2024-07-17 12:18 UTC, veksi requested changes
Ovo je sad super :)
Pogledaj malo komentare (više je kozmetički) ali ima mi smisla da to dodaš :)

2024-07-17 12:18 UTC, veksi commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +  const { mutate } = useSWR(swrKeys.me, fetcher);
Ovo je okejish, dosao si do mutate funkcije za cache, ali na mjestu gdje koristis `LoginForm` (page) vec koristis `AuthRedirect` koji u sebi ima ovaj isti useSWR hook.
U ovom slučaju će se na page-u 2 put pozivati ovaj fetcher (istina, neće uvijek ići na API zbog cache-a) ali nema potrebe.
Možeš koristiti globalni mutate:
https://swr.vercel.app/docs/mutation#global-mutate (ovaj koji importas iz swr-a)

2024-07-17 12:18 UTC, veksi commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +        <FormControl isRequired={true} isInvalid={!!errors.email}>
Nisam siguran da ce ti se triggerati validacije u useForm ako imas ovaj isRequired

2024-07-17 12:18 UTC, veksi commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +          {errors.email && <Text color="red.500">{errors.email.message}</Text>}
Pogledaj si `FormErrorMessage` komponentu od Chakre. U tom slucaju ti ne treba ovaj conditional render, već će se ona sama rendereati (conditionally) u slučaju da FormControl ima `isInvalid={ true}`

2024-07-17 12:18 UTC, veksi commented on tv-shows/src/components/features/shows/ShowReviewForm/ShowReviewForm.tsx
> +        <FormErrorMessage>
Ovdje koristis ono sto sam ti komentirao gore

2024-07-17 12:18 UTC, veksi commented on tv-shows/src/components/shared/stars/StarsRatingInput.tsx
> +        <StarInput id="1" register={register} />
Za sad je ovo okejish, možemo ovo i elegantnije riješiti.
Prođemo to nekad u sljedećim predavanjima (zadaćama)

2024-07-17 12:49 UTC, dadadavorin commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +  const { mutate } = useSWR(swrKeys.me, fetcher);
zamjenio sa globalnim 👍

2024-07-17 12:50 UTC, dadadavorin commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +        <FormControl isRequired={true} isInvalid={!!errors.email}>
maknuo gdje se koristilo, nisu se triggerale validacije zbog toga jel je prvo browser zahtjevao da se popune polja

2024-07-17 12:50 UTC, dadadavorin commented on tv-shows/src/components/features/auth/LoginForm/LoginForm.tsx
> +          {errors.email && <Text color="red.500">{errors.email.message}</Text>}
zamjenio custom sa `FormErrorMessage`

2024-07-18 07:09 UTC, veksi approved these changes
🥇

2024-07-18 07:09 UTC, merged